[build]
  functions = "netlify/functions"

[build.environment]
  NETLIFY_SKIP_SECURITY_CHECKS = "1"
  SECRETS_SCAN_OMIT_KEYS = "APP_URL"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
